apiVersion: 1

datasources:
  - name: Graphyard InfluxDB
    uid: graphyard-influxdb
    type: influxdb
    access: proxy
    url: http://graphyard-influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: InfluxQL
      dbName: ${GRAPHYARD_INFLUX_DB}
      httpMode: POST
    user: ${GRAPHYARD_INFLUX_USER}
    secureJsonData:
      password: ${GRAPHYARD_INFLUX_PASSWORD}
