# Generated by Django 6.0.3 on 2026-03-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConditionDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                ("metric_name", models.CharField(max_length=255)),
                ("host_filter", models.CharField(blank=True, max_length=128)),
                ("service_filter", models.CharField(blank=True, max_length=128)),
                ("tags_filter", models.JSONField(blank=True, default=dict)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", ">"),
                            ("gte", ">="),
                            ("lt", "<"),
                            ("lte", "<="),
                        ],
                        default="gt",
                        max_length=8,
                    ),
                ),
                ("warning_threshold", models.FloatField(blank=True, null=True)),
                ("critical_threshold", models.FloatField(blank=True, null=True)),
                ("window_minutes", models.PositiveIntegerField(default=30)),
                ("breach_minutes", models.PositiveIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="ok",
                        max_length=16,
                    ),
                ),
                ("last_evaluated", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True)),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "condition_definition",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host_id", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("grafana_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "host registry",
                "db_table": "host_registry",
                "ordering": ["host_id"],
            },
        ),
        migrations.CreateModel(
            name="IngestToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("token_hash", models.CharField(max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ingest_token",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PipelineHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "pipeline_heartbeat",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ServiceRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("grafana_url", models.URLField(blank=True)),
                ("enabled", models.BooleanField(default=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="graphyard.hostregistry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "service registry",
                "db_table": "service_registry",
                "ordering": ["service_id"],
            },
        ),
    ]
