# Generated by Django 6.0.3 on 2026-03-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphyard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricCollectionSpec",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "spec_type",
                    models.CharField(
                        choices=[("home_assistant_sensor", "Home Assistant Sensor")],
                        default="home_assistant_sensor",
                        max_length=64,
                    ),
                ),
                ("interval_seconds", models.PositiveIntegerField(default=60)),
                (
                    "next_run_time",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Unix timestamp for next scheduled execution",
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "metric_collection_spec",
                "ordering": ["name"],
            },
        ),
    ]
