# Generated by Django 6.0.3 on 2026-03-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphyard", "0002_metriccollectionspec"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metriccollectionspec",
            name="spec_type",
            field=models.CharField(
                choices=[
                    ("home_assistant_sensor", "Home Assistant Sensor"),
                    ("http_json_metric", "HTTP JSON Metric"),
                ],
                default="home_assistant_sensor",
                max_length=64,
            ),
        ),
    ]
