# Generated by Django 6.0.3 on 2026-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphyard', '0004_alter_metriccollectionspec_spec_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditiondefinition',
            name='subject_id_filter',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='conditiondefinition',
            name='subject_type_filter',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.CreateModel(
            name='SubjectRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('host', 'Host'), ('network_device', 'Network Device'), ('environment_sensor', 'Environment Sensor'), ('service', 'Service')], max_length=32)),
                ('subject_id', models.CharField(max_length=128)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_system', models.CharField(blank=True, max_length=64, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'subject registry',
                'db_table': 'subject_registry',
                'ordering': ['subject_type', 'subject_id'],
                'constraints': [models.UniqueConstraint(fields=('subject_type', 'subject_id'), name='subject_registry_unique_subject')],
            },
        ),
    ]
