# Generated by Django 6.0.3 on 2026-03-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphyard", "0005_conditiondefinition_subject_id_filter_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="metriccollectionspec",
            name="spec_type",
            field=models.CharField(
                choices=[
                    ("home_assistant_sensor", "Home Assistant Sensor"),
                    ("home_assistant_env_scan", "Home Assistant Env Scan"),
                    ("http_json_metric", "HTTP JSON Metric"),
                    ("unifi_device_traffic", "UniFi Device Traffic"),
                ],
                default="home_assistant_sensor",
                max_length=64,
            ),
        ),
    ]
