# Generated by Django 6.0.3 on 2026-09-19 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphyard", "0007_alter_metriccollectionspec_spec_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryHost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("warning_after_seconds", models.PositiveIntegerField(default=172800)),
                ("alert_when_stale", models.BooleanField(default=True)),
                (
                    "host",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="graphyard.hostregistry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphyard.inventoryhost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("snapshot_id", models.UUIDField()),
                ("observed_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("digest", models.CharField(max_length=64)),
                ("report", models.JSONField()),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="graphyard.inventoryhost",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="graphyard.inventoryhost",
                    ),
                ),
                (
                    "latest_attempt",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_attempts",
                        to="graphyard.inventorysnapshot",
                    ),
                ),
                (
                    "latest_success",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="category_successes",
                        to="graphyard.inventorysnapshot",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="inventorysnapshot",
            index=models.Index(
                fields=["host", "observed_at"], name="inventory_host_time"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorysnapshot",
            constraint=models.UniqueConstraint(
                fields=("host", "snapshot_id"), name="inventory_snapshot_identity"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventorycategory",
            constraint=models.UniqueConstraint(
                fields=("host", "name"), name="inventory_host_category"
            ),
        ),
    ]
