# Generated by Django 6.0.3 on 2026-09-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphyard', '0008_inventoryhost_inventorycredential_inventorysnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRelease',
            fields=[
                ('source_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition', models.JSONField()),
                ('enabled', models.BooleanField(default=True)),
                ('attempted_at', models.DateTimeField(null=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('version', models.CharField(blank=True, max_length=160)),
                ('error', models.CharField(blank=True, max_length=80)),
            ],
        ),
    ]
