# Generated by Django 6.0.8 on 2026-10-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("graphyard", "0009_inventoryrelease"),
    ]

    operations = [
        migrations.AddField(
            model_name="conditiondefinition",
            name="alert_when_stale",
            field=models.BooleanField(
                default=True,
                help_text="Untick for intermittent hosts: stale or missing data then reports ok ('not alerting') instead of warning.",
            ),
        ),
        migrations.AddField(
            model_name="conditiondefinition",
            name="stale_after_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Seconds the newest sample may age before the condition turns warning. Empty uses the global GRAPHYARD_CONDITION_DATA_STALE_WARNING_SECONDS.",
                null=True,
            ),
        ),
    ]
